---
title: Services and Drivers
description: Configures services and drivers to reduce background system resource utilization
onUpgrade: false
actions:
  # ----------------------------------
  # - Potential references           -
  # - Mostly upon IoT recommendation -
  # ----------------------------------
  # https://learn.microsoft.com/en-us/windows-server/remote/remote-desktop-services/rds-vdi-recommendations-2004
  # https://learn.microsoft.com/en-us/windows-server/security/windows-services/security-guidelines-for-disabling-system-services-in-windows-server
  # https://learn.microsoft.com/en-us/windows/iot/iot-enterprise/optimize/services

  # Back up default Windows services & drivers
  - !powerShell:
    command: |
      .\BACKUP.ps1 -FilePath """$([Environment]::GetFolderPath('Windows'))\AtlasModules\Other\winServices.reg"""
    wait: true
    exeDir: true

  ##############################################################################################
  ## SCRIPTS                                                                                  ##
  ##############################################################################################

  - !writeStatus: {status: 'Disabling File Sharing'}
  - !powerShell:
    command: '.\AtlasModules\Scripts\ScriptWrappers\DisableFileSharing.ps1 -Silent'
    exeDir: true
    wait: true
    runas: currentUserElevated

  - !writeStatus: {status: 'Disabling Location'}
  - !powerShell:
    command: |
      Start-Process -FilePath (Join-Path $env:windir 'AtlasDesktop\3. General Configuration\Location\Disable Location (default).cmd') -ArgumentList '/silent' -Wait
    exeDir: true
    wait: true
    runas: currentUserElevated

  - !writeStatus: {status: 'Disabling Indexing'}
  - !powerShell:
    command: |
      Start-Process -FilePath (Join-Path $env:windir 'AtlasDesktop\3. General Configuration\Search Indexing\Disable Search Indexing (default).cmd') -ArgumentList '/silent' -Wait
    exeDir: true
    wait: true
    runas: currentUserElevated

  - !writeStatus: {status: 'Disabling optional services'}
  - !powerShell:
    command: |
      $scripts = @(
          'AtlasDesktop\6. Advanced Configuration\Services\Printing\Disable Printing (default).cmd',
          'AtlasDesktop\6. Advanced Configuration\Services\Bluetooth\Disable Bluetooth (default).cmd',
          'AtlasDesktop\6. Advanced Configuration\Services\Network Discovery\Disable Network Discovery Services (default).cmd',
          'AtlasDesktop\6. Advanced Configuration\Services\Lanman Workstation (SMB)\Disable Lanman Workstation (default).cmd',
          'AtlasDesktop\6. Advanced Configuration\Services\Superfetch\Disable SuperFetch (default).cmd'
      )
      foreach ($script in $scripts) {
          Start-Process -FilePath (Join-Path $env:windir $script) -ArgumentList '/silent' -Wait
      }
    exeDir: true
    wait: true
    runas: currentUserElevated

  ##############################################################################################
  ## SERVICES                                                                                 ##
  ##############################################################################################

  - !writeStatus: {status: 'Configuring services'}

    # ------ Microsoft recommendation - 'OK to disable' ------
  - !service: {name: 'OneSyncSvc', operation: change, startup: 4, ignoreErrors: true}
  - !service: {name: 'TrkWks', operation: change, startup: 4, ignoreErrors: true}
  - !service: {name: 'PcaSvc', operation: change, startup: 4, ignoreErrors: true}
  - !service: {name: 'DiagTrack', operation: change, startup: 4, ignoreErrors: true}

    # ------ Microsoft recommendation - 'Do not disable' -----
  - !service: {name: 'diagnosticshub.standardcollector.service', operation: change, startup: 4, ignoreErrors: true}
  - !service: {name: 'WerSvc', operation: change, startup: 4, ignoreErrors: true}

    # ------- Microsoft recommendation - 'No guidance' ------
  - !service: {name: 'wercplsupport', operation: change, startup: 4, ignoreErrors: true}
  - !service: {name: 'UCPD', operation: change, startup: 4, ignoreErrors: true}

    # ------ Atlas Lite service defaults ------
  - !service: {name: 'CscService', operation: change, startup: 4, ignoreErrors: true}
  - !service: {name: 'MapsBroker', operation: change, startup: 3, ignoreErrors: true}
  - !service: {name: 'RemoteAccess', operation: change, startup: 4, ignoreErrors: true}
  - !service: {name: 'RemoteRegistry', operation: change, startup: 4, ignoreErrors: true}
  - !service: {name: 'StorSvc', operation: change, startup: 3, ignoreErrors: true}
  - !service: {name: 'SharedAccess', operation: change, startup: 4, ignoreErrors: true}
  - !service: {name: 'TermService', operation: change, startup: 3, ignoreErrors: true}
  - !service: {name: 'TroubleshootingSvc', operation: change, startup: 3, ignoreErrors: true}
  - !service: {name: 'seclogon', operation: change, startup: 3, ignoreErrors: true}
  - !service: {name: 'ssh-agent', operation: change, startup: 4, ignoreErrors: true}

  ##############################################################################################
  ## DRIVERS                                                                                  ##
  ##############################################################################################

  - !writeStatus: {status: 'Configuring drivers'}

  - !service: {name: 'GpuEnergyDrv', operation: change, startup: 4, ignoreErrors: true}
    # NetBios support can be enabled with the file sharing script
  - !service: {name: 'NetBT', operation: change, startup: 4, ignoreErrors: true}
  - !service: {name: 'Telemetry', operation: change, startup: 4, ignoreErrors: true}
