---
title: Disable Compact Mode
description: Disables compact mode in File Explorer
builds: [ '>=22000' ]
actions:
  - !registryValue:
    path: 'HKCU\Software\Microsoft\Windows\CurrentVersion\Explorer\Advanced'
    value: 'UseCompactMode'
    data: '0'
    type: REG_DWORD
    
    
